- name: Setup Vprofile Bastion Host
  hosts: localhost
  connection: localhost
  gather_facts: False
  tasks:
    - name: Import VPC setup variables
      include_vars: vars/bastion_setup

    - name: Import VPC setup Variable
      include_vars: vars/output_vars
    
    - name: Create vprofile ec2 key
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out

    - name: Save private key into file bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed
    
    - name: creating sg for Bastion Host
      ec2_group:
        name: Bastion-host-sg
        description: allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
      register: BastionSG_out

    - name: Creating Bastion Host
      ec2_instance:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t3.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instace_tags: 
          Name: "Bastion_host"
          Project: Vprofile
          Owner: Devops Team
        exact_count: 1
        count_tag:
          Name: "Bastion_host"
          Project: Vprofile
          Owner: Devops Team
        group_id: "{{BastionSG_out.group_id}}"
      register: bastionHost_out