---
- name: Deploy SQL file on accounts db
  hosts: dbsrvgrp
  gather_facts: no
  tasks:
    - name: copy sql to dbsrvgrp
      copy:
        src: files/db_backup.sql
        dest: /tmp/db_backup.sql
      tags:
        - deploy 
    
    - name: Restoring db
      mysql_db:
        name: accounts
        login_user: "{{dbuser}}"
        login_password: "{{dbpass}}"
        state: import
        target: /tmp/db_backup.sql
      notify:
        - Restart mysql
      tags:
        - deploy
    